name: Check Set-Up & Build

on:
  workflow_dispatch:
  pull_request:
    branches: [ 'develop*', master ]
    paths: [ 'node/**', 'pallets/**', 'runtime/**', 'primitives/**' ]

jobs:
  check-build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set-Up
        run: sudo apt install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl

      - name: Install Rustup
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source ~/.cargo/env
          ./scripts/init.sh

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check Build
        run: |
          SKIP_WASM_BUILD=1 cargo check --release --all-targets --all-features
